### ISSUE TITLE
Please do not put AppImage into .tar.gz

### ISSUE THREAD

**Issue by probonopd** [KangLin/SerialPortAssistant#2]
Please do not put AppImage into .tar.gz. Instead, please put the AppImage file on GitHub Releases for direct download.

```
./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -appimage
wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
bash upload.sh Serial*.AppImage* ##### <------- not in a .tar.gz
```

https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#common-mistake

**Comment by probonopd** [comment]
If you want automatic updates, please ping me once you have changed this. I can show you a way how to get automatic updates easily.

**Comment by KangLin** [comment]
Yes, I want automatic updates.

**Comment by probonopd** [comment]
@antony-jr has made a Qt plugin that can do it easily. Please see: https://github.com/TheFutureShell/updatedeployqt

Examples how to use:
* https://github.com/antony-jr/blue-glow
* https://github.com/antony-jr/QTalarm-AppImage

**Comment by antony-jr** [comment]
@probonopd If its pure Qt and the author has time to nitpick and review my PR's then I advice to use the library instead. This is because the tool is still in alpha and some latest bug fixes are not used by the plugin. Also I still did not translate any constant English sentences in the GUI. This application seems to use a different language. A little help on the translation can help or I will use google translate. (or something qt specific)

qTox already started using AppImage update feature using the library. See https://github.com/qTox/qTox/pull/5747 , Try it by downloading the latest nightly release from qTox -> https://github.com/qTox/qTox-nightly-releases/releases/tag/ci-master-latest

**PS**: I have no experience in creating application for languages other than English even though its not my mother tongue.

**Comment by antony-jr** [comment]
@KangLin just let me know if you want to use this library in your Application -> https://antony-jr.github.io/AppImageUpdaterBridge to enable the **AppImage delta update feature** for your appimage. There is also the official AppImage update library -> https://github.com/AppImage/AppImageUpdate which is vaguely documented here -> https://docs.appimage.org/introduction/software-overview.html#appimageupdate

**Or** if you want to use the **updatedeployqt** I can write the configuration file for you.
